---

- name: Get list of installed kibana plugins
  shell: >
      {{ kibana_bin_dir }}/kibana-plugin list {{ _list_plugins_cmd_filter|default('') }}
  register: plugins

- debug: msg="Installed plugins - {{ plugins.stdout_lines|join(', ') }}"

- name: Remove installed kibana plugins before update
  shell: >
      {{ kibana_bin_dir }}/kibana-plugin remove {{ item }}
  with_items: "{{ kibana_plugins_install|intersect(plugins.stdout_lines) }}"
  when: kibana_update_plugins

- name: Install kibana plugins
  shell: >
      {{ kibana_bin_dir }}/kibana-plugin install {{ item }}
  with_items: "{{ kibana_plugins_install }}"
  when: item not in plugins.stdout_lines and item not in kibana_plugins_remove

- name: Remove kibana plugins
  shell: >
      {{ kibana_bin_dir }}/kibana-plugin remove {{ item }}
  with_items: "{{ kibana_plugins_remove }}"
  when: item in plugins.stdout_lines
